apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer3
  namespace: orgx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer3
  template:
    metadata:
      labels:
        app: orderer3
    spec:
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.5
          env:
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /var/hyperledger/orderer/msp
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /var/hyperledger/orderer/tls/keystore/40e258b3d7d383188dca26a08010ee89603ffd14c99e63f23fcb0d18d7a27042_sk
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /var/hyperledger/orderer/tls/signcerts/cert.pem
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: /var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7054.pem
            - name: ORDERER_CHANNELPARTICIPATION_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
              value: none
            - name: ORDERER_ADMIN_LISTENADDRESS
              value: "0.0.0.0:7053"
            - name: ORDERER_ADMIN_TLS_ENABLED
              value: "true"
            - name: ORDERER_ADMIN_TLS_PRIVATEKEY
              value: /var/hyperledger/orderer/tls/keystore/40e258b3d7d383188dca26a08010ee89603ffd14c99e63f23fcb0d18d7a27042_sk
            - name: ORDERER_ADMIN_TLS_CERTIFICATE
              value: /var/hyperledger/orderer/tls/signcerts/cert.pem
            - name: ORDERER_ADMIN_TLS_ROOTCAS
              value: /var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7054.pem
            - name: ORDERER_ADMIN_TLS_CLIENTROOTCAS
              value: /var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7054.pem
          ports:
            - containerPort: 7050
            - containerPort: 7053
          volumeMounts:
            - name: msp
              mountPath: /var/hyperledger/orderer/msp
            - name: tls
              mountPath: /var/hyperledger/orderer/tls
      volumes:
        - name: msp
          hostPath:
            path: /home/asantopadre/fabric-deploy/orderer1-msp
        - name: tls
          hostPath:
            path: /home/asantopadre/fabric-deploy/orderer3-tls
